### ISSUE TITLE
REF and ALT alleles shouldn't match, but they do at these marker

### ISSUE THREAD

**Issue by Gabriel-Kirchgraber** [andrewparkermorgan/argyle#9]
Hi,
I had the same problem as a previous poster (#5) with the SNP_Map file provided by Neogene, it had the TOP/BOTTOM customer Strand etc. encoding for reference and alt alleles. I followed your advice and constructed them myself from my samples (31), but for some SNPs there is no alternative allele, it's the same in all samples, so I get the above warning. Does this pose a problem for further analysis? For example if I start comparing to the consensus calls of other strains/substrains where an alternative allele exists. Maybe I should construct new ref/alt allele map with the consensus calls? I am doing the new miniMuga v2 assay and have consensus calls for ca. 300 strains/substrains.
Best, Gabriel.

**Comment by andrewparkermorgan** [comment]
Gabriel,

The best resource for creating a market map for any of the MUGA platforms is probably this repository from Karl Broman: https://github.com/kbroman/MUGAarrays

He has created files with chromosome, physical position, genetic position, ref and alt alleles (and strand with respect to reference genome) for MiniMUGA. You should be able to use that to make the maker map required by argyle.

I find the reporting of strandedness from Neogen to be quite confusing.

APM

**Comment by Gabriel-Kirchgraber** [comment]
Thanks! I will check it out! I also kind of despaired trying to figure out how the Neogene strand designations worked and was quite relieved to discover that even the author of the tool didn't get it ;-).
